name: Awesome Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # Run daily at 2 AM UTC to catch any upstream changes
    - cron: '0 2 * * *'

jobs:
  awesome-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run awesome-lint
        run: npx awesome-lint

      - name: Check for broken links (optional)
        run: |
          # Install markdown-link-check
          npm install -g markdown-link-check

          # Check for broken links with custom config
          markdown-link-check README.md \
            --config .github/workflows/markdown-link-check-config.json \
            || echo "⚠️ Some links may be temporarily unavailable"
        continue-on-error: true
